// <auto-generated />
using System;
using CA.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CA.Persistance.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201017100039_Initial-commit-Application")]
    partial class InitialcommitApplication
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CA.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Chapter")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Meaning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Synonmys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Verse")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32fcf429-6982-49ba-ad30-ae4818d90c96"),
                            Chapter = 1,
                            Description = "dhrtarastra uvaca dharma-ksetre kuru-ksetre samaveta yuyutsavah    mamakah pandavas caiva    kim akurvata sanjaya",
                            Meaning = "Dhrtarastra said: O Sanjaya, after assembling in the place of pilgrimage at Kuruksetra, what did my sons and the sons of Pandu do, being desirous to fight?",
                            SerialNumber = 0,
                            Synonmys = "sanjayah--Sanjaya; uvaca--said; drstva--after seeing; tu--but; pandavaanikam--the soldiers of the Pandavas; vyudham--arranged in military phalanx; duryodhanah--King Duryodhana; tada--at that time; acaryam--the teacher; upasangamya--approaching nearby; raja--the king; vacanam--words; abravit--spoke.",
                            Verse = 1
                        },
                        new
                        {
                            Id = new Guid("c983bb6a-8f1e-4b1b-a1b6-2751375f80ad"),
                            Chapter = 1,
                            Description = "sanjaya uvaca    drstva tu pandavanikam    vyudham duryodhanas tada    acaryam upasangamya    raja vacanam abravit",
                            Meaning = "Sanjaya said: O King, after looking over the army gathered by the sons of Pandu, King Duryodhana went to his teacher and began to speak the following words:",
                            SerialNumber = 0,
                            Synonmys = "pasya--behold; etam--this; pandu-putranam--of the sons of Pandu; acarya--O teacher; mahatim--great; camum--military force; vyudham--arranged; drupada-putrena--by the son of Drupada; tava--your; sisyena--disciple; dhi-mata--very intelligent.",
                            Verse = 2
                        },
                        new
                        {
                            Id = new Guid("96d152e7-402e-47c9-9fae-612c077acc25"),
                            Chapter = 1,
                            Description = "pasyaitam pandu-putranam     acarya mahatim camum    vyudham drupada-putrena    tava sisyena dhimata",
                            Meaning = "O my teacher, behold the great army of the sons of Pandu, so expertly    arranged by your intelligent disciple, the son of Drupada.",
                            SerialNumber = 0,
                            Synonmys = "pasya--behold; etam--this; pandu-putranam--of the sons of Pandu;   acarya--O teacher; mahatim--great; camum--military force; vyudham--    arranged; drupada-putrena--by the son of Drupada; tava--your; sisyena--    disciple; dhi-mata--very intelligent.",
                            Verse = 3
                        });
                });

            modelBuilder.Entity("CA.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28da7440-0ee6-42ac-a683-31d170c9e693"),
                            CardId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Anger",
                            IsActive = true,
                            Name = "Anger"
                        },
                        new
                        {
                            Id = new Guid("cfe4e5b7-e2c1-402f-ba67-a367e886139f"),
                            CardId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Confusion",
                            IsActive = true,
                            Name = "Confusion"
                        },
                        new
                        {
                            Id = new Guid("de5f276c-bfc2-4724-b306-cc583614df62"),
                            CardId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Envy",
                            IsActive = true,
                            Name = "Envy"
                        });
                });

            modelBuilder.Entity("CA.Domain.Entities.Card", b =>
                {
                    b.HasOne("CA.Domain.Entities.Group", "Group")
                        .WithMany("Cards")
                        .HasForeignKey("GroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
