INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 5, N'dhrstaketus cekitanah    kasirajas ca viryavan    purujit kuntibhojas ca    saibyas ca nara-pungavah', N'dhrstaketuh--Dhrstaketu; cekitanah--Cekitana; kasirajah--Kasiraja; ca--also; virya-van--very powerful; purujit--Purujit; kuntibhojah--Kuntibhoja; ca--and; saibyah--Saibya; ca--and; nara-pungavah--heroes inhuman society.', N'There are also great, heroic, powerful fighters like Dhrstaketu,Cekitana, Kasiraja, Purujit, Kuntibhoja and Saibya.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 6, N'yudhamanyus ca vikranta    uttamaujas ca viryavan    saubhadro draupadeyas ca    sarva eva maha-rathah', N'yudhamanyuh--Yudhamanyu; ca--and; vikrantah--mighty; uttamaujah--Uttamauja; ca--and; virya-van--very powerful; saubhadrah--the son ofSubhadra; draupadeyah--the sons of Draupadi; ca--and; sarve--all; eva--certainly; maha-rathah--great chariot fighters.', N'There are the mighty Yudhamanyu, the very powerful Uttamauja, the son of Subhadra and the sons of Draupadi. All these warriors are great chariot fighters.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 7, N'asmakam tu visista ye    tan nibodha dvijottama    nayaka mama sainyasya    samjnartham tan bravimi te', N'asmakam--our; tu--but; visistah--especially powerful; ye--those; tan--them; nibodha--just take note, be informed; dvija-uttama--the best ofthe brahmanas; nayakah--captains; mama--my; sainyasya--of the soldiers;samjna-artham--for information; tan--them; bravimi--I am speaking; te--your.', N'O best of the brahmanas, for your information, let me tell you about the captains who are especially qualified to lead my military force. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 8, N'bhavan bhismas ca karnas ca    krpas ca samitim-jayah    asvatthama vikarnas ca    saumadattis tathaiva ca', N'bhavan--your self; bhismah--Grandfather Bhisma; ca--also; karnah--Karna; ca--and; krpah--Krpa; ca--and; samitim-jayah--always victoriousin battle; asvatthama--Asvatthama; vikarnah--Vikarna; ca--as well as;saumadattih--the son of Somadatta; tatha--and as; eva--certainly; ca--and.', N'There are personalities like yourself, Bhisma, Karna, Krpa, Asvatthama, Vikarna and the son of Somadatta called Bhurisrava, who are always victorious in battle.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 9, N'anye ca bahavah sura    mad-arthe tyakta-jivitah    nana-sastra-praharanah    sarve yuddha-visaradah', N'anye--many others; ca--also; bahavah--in great numbers; surah--heroes;mat-arthe--for my sake; tyakta-jivitah--prepared to risk life; nana--many; sastra--weapons; praharanah--equipped with; sarve--all of them;yuddha--battle; visaradah--experienced in military science.', N'There are many other heroes who are prepared to lay down their lives for my sake. All of them are well equipped with different kinds of weapons, and all are experienced in military science.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 10, N'aparyaptam tad asmakam    balam bhismabhiraksitam    paryaptam tv idam etesam    balam bhimabhiraksitam', N'aparyaptam--immeasurable; tat--that; asmakam--of ours; balam--strength;bhisma--by Grandfather Bhisma; abhiraksitam--perfectly protected;paryaptam--limited; tu--but; idam--all this; etesam--of the Pandavas;balam--strength; bhima--by Bhima; abhiraksitam--carefully protected.', N'Our strength is immeasurable, and we are perfectly protected by Grandfather Bhisma, whereas the strength of the Pandavas, carefully protected by Bhima, is limited.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 11, N'ayanesu ca sarvesu    yatha-bhagam avasthitah    bhismam evabhiraksantu    bhavantah sarva eva hi', N'ayanesu--in the strategic points; ca--also; sarvesu--everywhere; yathabhagam--as they are differently arranged; avasthitah--situated;bhismam--unto Grandfather Bhisma; eva--certainly; abhiraksantu--supportmay be given; bhavantah--all of you; sarve--respectively; eva--certainly; hi--and exactly.', N'Now all of you must give full support to Grandfather Bhisma, standing at your respective strategic points in the phalanx of the army. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 12, N'tasya sanjanayan harsam    kuru-vrddhah pitamahah    simha-nadam vinadyoccaih    sankham dadhmau pratapavan', N'tasya--his; sanjanayan--increasing; harsam--cheerfulness; kuru-vrddhah--the grandsire of the Kuru dynasty (Bhisma); pitamahah--thegrandfather; simha-nadam--roaring sound, like a lion; vinadya--vibrating; uccaih--very loudly; sankham--conchshell; dadhmau--blew;pratapa-van--the valiant.', N'Then Bhisma, the great valiant grandsire of the Kuru dynasty, the grandfather of the fighters, blew his conchshell very loudly, like the sound of a lion, giving Duryodhana joy.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 13, N'tatah sankhas ca bheryas ca    panavanaka-gomukhah    sahasaivabhyahanyanta    sa sabdas tumulo bhavat', N'tatah--thereafter; sankhah--conchshells; ca--also; bheryah--bugles; ca--and; panava-anaka--trumpets and drums; go-mukhah--horns; sahasa--allof a sudden; eva--certainly; abhyahanyanta--being simultaneouslysounded; sah--that; sabdah--combined sound; tumulah--tumultuous;abhavat--became.', N'After that, the conchshells, bugles, trumpets, drums and horns were all suddenly sounded, and the combined sound was tumultuous. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 14, N'tatah svetair hayair yukte    mahati syandane sthitau    madhavah pandavas caiva    divyau sankhau pradadhmatuh', N'tatah--thereafter; svetaih--by white; hayaih--horses; yukte--beingyoked; mahati--in a great; syandane--chariot; sthitau--so situated;madhavah--Krsna (the husband of the goddess of fortune); pandavah--Arjuna (the son of Pandu); ca--also; eva--certainly; divyau--transcendental; sankhau--conchshells; pradadhmatuh--sounded.', N'On the other side, both Lord Krsna and Arjuna, stationed on a great chariot drawn by white horses, sounded their transcendental conchshells.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 15, N'pancajanyam hrsikeso    devadattam dhananjayah    paundram dadhmau maha-sankham    bhima-karma vrkodarah', N'pancajanyam--the conchshell named Pancajanya; hrsika-isah--Hrsikesa(Krsna, the Lord who directs the senses of the devotees); devadattam--the conchshell named Devadatta; dhanam-jayah--Dhananjaya (Arjuna, thewinner of wealth); paundram--the conch named Paundra; dadhmau--blew; maha-sankham--the terrific conchshell; bhima-karma--one who performs herculean tasks; vrka-udarah--the voracious eater (Bhima).', N'Then, Lord Krsna blew His conchshell, called Pancajanya; Arjuna blew his, the Devadatta; and Bhima, the voracious eater and performer of herculean tasks, blew his terrific conchshell called Paundra.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 19, N'sa ghoso dhartarastranam    hrdayani vyadarayat    nabhas ca prthivim caiva    tumulo bhyanunadayan', N'sah--that; ghosah--vibration; dhartarastranam--of the sons ofDhrtarastra; hrdayani--hearts; vyadarayat--shattered; nabhah--the sky;ca--also; prthivim--the surface of the earth; ca--also; eva--certainly;tumulah--uproarious; abhyanunadayan--by resounding.', N'The blowing of these different conchshells became uproarious, and thus, vibrating both in the sky and on the earth, it shattered the hearts of the sons of Dhrtarastra.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 20, N'atha vyavasthitan drstva    dhartarastran kapi-dhvajah    pravrtte sastra-sampate    dhanur udyamya pandavah    hrsikesam tada vakyam    idam aha mahi-pate', N'atha--thereupon; vyavasthitan--situated; drstva--looking upon;dhartarastran--the sons of Dhrtarastra; kapi-dhvajah--one whose flag ismarked with Hanuman; pravrtte--while about to engage; sastra-sampate--the arrows released; dhanuh--bow; udyamya--after taking up; pandavah--the son of Pandu (Arjuna); hrsikesam--unto Lord Krsna; tada--at that time; vakyam--words; idam--these; aha--said; mahi-pate--O King.', N'O King, at that time Arjuna, the son of Pandu, who was seated in his chariot, bearing the flag marked with Hanuman, took up his bow and prepared to shoot his arrows, looking at the sons of Dhrtarastra. O King, Arjuna then spoke to Hrsikesa [Krsna] these words:');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 23, N'yotsyamanan avekse ham    ya ete tra samagatah    dhartarastrasya durbuddher    yuddhe priya-cikirsavah', N'yotsyamanan--those who will be fighting; avekse--let me see; aham--I;ye--who; ete--those; atra--here; samagatah--assembled; dhartarastrasya--the son of Dhrtarastra; durbuddheh--evil-minded; yuddhe--in the fight;priya--well; cikirsavah--wishing.', N'Let me see those who have come here to fight, wishing to please the evil-minded son of Dhrtarastra. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 24, N'sanjaya uvaca    evam ukto hrsikeso    gudakesena bharata    senayor ubhayor madhye    sthapayitva rathottamam', N'sanjayah--Sanjaya; uvaca--said; evam--thus; uktah--addressed;hrsikesah--Lord Krsna; gudakesena--by Arjuna; bharata--O descendant ofBharata; senayoh--of armies; ubhayoh--of both; madhye--in the midst of;sthapayitva--by placing; ratha-uttamam--the finest chariot.', N'Sanjaya said: O descendant of Bharata, being thus addressed by Arjuna, Lord Krsna drew up the fine chariot in the midst of the armies of both parties.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 25, N'bhisma-drona-pramukhatah    sarvesam ca mahi-ksitam    uvaca partha pasyaitan    samavetan kurun iti', N'bhisma--Grandfather Bhisma; drona--the teacher Drona; pramukhatah--infront of; sarvesam--all; ca--also; mahi-ksitam--chiefs of the world;uvaca--said; partha--O Partha (son of Prtha); pasya--just behold; etan--all of them; samavetan--assembled; kurun--all the members of the Kuru dynasty; iti--thus.', N'In the presence of Bhisma, Drona and all other chieftains of the world, Hrsikesa, the Lord, said, Just behold, Partha, all the Kurus who are assembled here.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 26, N'tatrapasyat sthitan parthah    pitrn atha pitamahan    acaryan matulan bhratrn    putran pautran sakhims tatha    svasuran suhrdas caiva    senayor ubhayor api', N'tatra--there; apasyat--he could see; sthitan--standing; parthah--Arjuna; pitrn--fathers; atha--also; pitamahan--grandfathers; acaryan--teachers; matulan--maternal uncles; bhratrn--brothers; putran--sons;pautran--grandsons; sakhin--friends; tatha--too; svasuran--fathers-inlaw; suhrdah--well-wishers; ca--also; eva--certainly; senayoh--of the armies; ubhayoh--of both parties; api--including.', N'There Arjuna could see, within the midst of the armies of both parties, his fathers, grandfathers, teachers, maternal uncles, brothers, sons, grandsons, friends, and also his father-in-law and well-wishers--all present there.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 27, N'tan samiksya sa kaunteyah    sarvan bandhun avasthitan    krpaya parayavisto    visidann idam abravit', N'tan--all of them; samiksya--after seeing; sah--he; kaunteyah--the sonof Kunti; sarvan--all kinds of; bandhun--relatives; avasthitan--situated; krpaya--by compassion; paraya--of a high grade; avistah--overwhelmed by; visidan--while lamenting; idam--thus; abravit--spoke.', N'When the son of Kunti, Arjuna, saw all these different grades of friends and relatives, he became overwhelmed with compassion and spoke thus');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 28, N'arjuna uvaca    drstvemam sva-janam krsna    yuyutsum samupasthitam    sidanti mama gatrani    mukham ca parisusyati', N'arjunah--Arjuna; uvaca--said; drstva--after seeing; imam--all these;sva-janam--kinsmen; krsna--O Krsna; yuyutsum--all in fighting spirit;samupasthitam--all present; sidanti--quivering; mama--my; gatrani--limbs of the body; mukham--mouth; ca--also; parisusyati--drying up.', N'Arjuna said: My dear Krsna, seeing my friends and relatives present before me in such a fighting spirit, I feel the limbs of my body quivering and my mouth drying up.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 29, N'vepathus ca sarire me    roma-harsas ca jayate    gandivam sramsate hastat    tvak caiva paridahyate', N'vepathuh--trembling of the body; ca--also; sarire--on the body; me--my;roma-harsah--standing of the hair on end; ca--also; jayate--is takingplace; gandivam--the bow of Arjuna; sramsate--is slipping; hastat--fromthe hands; tvak--skin; ca--also; eva--certainly; paridahyate--burning.', N'My whole body is trembling, and my hair is standing on end. My bow Gandiva is slipping from my hand, and my skin is burning. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 30, N'na ca saknomy avasthatum    bhramativa ca me manah    nimittani ca pasyami    viparitani kesava', N'na--nor; ca--also; saknomi--am I able; avasthatum--to stay; bhramati--forgetting; iva--as; ca--and; me--my; manah--mind; nimittani--causes;ca--also; pasyami--I foresee; viparitani--just the opposite; kesava--Okiller of the demon Kesi (Krsna).', N'I am now unable to stand here any longer. I am forgetting myself, and my mind is reeling. I foresee only evil, O killer of the Kesi demon. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 31, N'na ca sreyo nupasyami    hatva sva-janam ahave    na kankse vijayam krsna    na ca rajyam sukhani ca', N'na--nor; ca--also; sreyah--good; anupasyami--do I foresee; hatva--bykilling; sva-janam--own kinsmen; ahave--in the fight; na--nor; kankse--do I desire; vijayam--victory; krsna--O Krsna; na--nor; ca--also;rajyam--kingdom; sukhani--happiness thereof; ca--also.', N'I do not see how any good can come from killing my own kinsmen in this battle, nor can I, my dear Krsna, desire any subsequent victory, kingdom, or happiness.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 36, N'papam evasrayed asman    hatvaitan atatayinah    tasman narha vayam hantum    dhartarastran sa-bandhavan    sva-janam hi katham hatva    sukhinah syama madhava', N'papam--vices; eva--certainly; asrayet--must take upon; asman--us;hatva--by killing; etan--all these; atatayinah--aggressors; tasmat--therefore; na--never; arhah--deserving; vayam--we; hantum--to kill;dhartarastran--the sons of Dhrtarastra; sa-bandhavan--along with friends; sva-janam--kinsmen; hi--certainly; katham--how; hatva--by killing; sukhinah--happy; syama--become; madhava--O Krsna, husband of the goddess of fortune.', N'Sin will overcome us if we slay such aggressors. Therefore it is not proper for us to kill the sons of Dhrtarastra and our friends. What should we gain, O Krsna, husband of the goddess of fortune, and how could we be happy by killing our own kinsmen?');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 39, N'kula-ksaye pranasyanti    kula-dharmah sanatanah    dharme naste kulam krtsnam    adharmo bhibhavaty uta', N'kula-ksaye--in destroying the family; pranasyanti--becomes vanquished;kula-dharmah--the family traditions; sanatanah--eternal; dharme--inreligion; naste--being destroyed; kulam--family; krtsnam--wholesale;adharmah--irreligious; abhibhavati--transforms; uta--it is said.', N'With the destruction of dynasty, the eternal family tradition is vanquished, and thus the rest of the family becomes involved in irreligious practice.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 40, N'adharmabhibhavat krsna    pradusyanti kula-striyah    strisu dustasu varsneya    jayate varna-sankarah', N'adharma--irreligion; abhibhavat--having become predominant; krsna--OKrsna; pradusyanti--become polluted; kula-striyah--family ladies;strisu--of the womanhood; dustasu--being so polluted; varsneya--Odescendant of Vrsni; jayate--it so becomes; varna-sankarah--unwanted progeny.', N'When irreligion is prominent in the family, O Krsna, the women of the family become corrupt, and from the degradation of womanhood, O descendant of Vrsni, comes unwanted progeny.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 41, N'sankaro narakayaiva    kula-ghnanam kulasya ca    patanti pitaro hy esam    lupta-pindodaka-kriyah', N'sankarah--such unwanted children; narakaya--for hellish life; eva--certainly; kula-ghnanam--of those who are killers of the family;kulasya--of the family; ca--also; patanti--fall down; pitarah--forefathers; hi--certainly; esam--of them; lupta--stopped; pinda-- offerings; udaka--water; kriyah--performances.', N'When there is increase of unwanted population, a hellish situation is created both for the family and for those who destroy the family tradition. In such corrupt families, there is no offering of oblations of food and water to the ancestors.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 42, N'dosair etaih kula-ghnanam    varna-sankara-karakaih    utsadyante jati-dharmah    kula-dharmas ca sasvatah', N'dosaih--by such faults; etaih--all these; kula-ghnanam--of thedestroyer of the family; varna-sankara--unwanted children; karakaih--bythe doers; utsadyante--causes devastation; jati-dharmah--communityprojects; kula-dharmah--family traditions; ca--also; sasvatah--eternal.', N'Due to the evil deeds of the destroyers of family tradition, all kinds of community projects and family welfare activities are devastated. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 43, N'utsanna-kula-dharmanam    manusyanam janardana    narake niyatam vaso    bhavatity anususruma', N'utsanna--spoiled; kula-dharmanam--of those who have the familytraditions; manusyanam--of such men; janardana--O Krsna; narake--inhell; niyatam--always; vasah--residence; bhavati--it so becomes; iti--thus; anususruma--I have heard by disciplic succession.', N'O Krsna, maintainer of the people, I have heard by disciplic succession that those who destroy family traditions dwell always in hell. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 44, N'aho bata mahat papam    kartum vyavasita vayam    yad rajya-sukha-lobhena    hantum sva-janam udyatah', N'aho--alas; bata--how strange it is; mahat--great; papam--sins; kartum--to perform; vyavasitah--decided; vayam--we; yat--so that; rajya--kingdom; sukha-lobhena--driven by greed for royal happiness; hantum--tokill; sva-janam--kinsmen; udyatah--trying for.', N'Alas, how strange it is that we are preparing to commit greatly sinful acts, driven by the desire to enjoy royal happiness. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 45, N'yadi mam apratikaram    asastram sastra-panayah    dhartarastra rane hanyus    tan me ksemataram bhavet', N'yadi--even if; mam--unto me; apratikaram--without being resistant;asastram--without being fully equipped; sastra-panayah--those withweapons in hand; dhartarastrah--the sons of Dhrtarastra; rane--in thebattlefield; hanyuh--may kill; tat--that; me--mine; ksema-taram--better; bhavet--become.', N'I would consider it better for the sons of Dhrtarastra to kill me unarmed and unresisting, rather than to fight with them. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 1, 46, N'sanjaya uvaca    evam uktvarjunah sankhye    rathopastha upavisat    visrjya sa-saram capam    soka-samvigna-manasah', N'sanjayah--Sanjaya; uvaca--said; evam--thus; uktva--saying; arjunah--Arjuna; sankhye--in the battlefield; ratha--chariot; upasthe--situatedon; upavisat--sat down again; visrjya--keeping aside; sa-saram--alongwith arrows; capam--the bow; soka--by lamentation; samvigna--distressed; manasah--within the mind.', N'Sanjaya said: Arjuna, having thus spoken on the battlefield, cast aside his bow and arrows and sat down on the chariot, his mind overwhelmed with grief.');
