
INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 1, N'sanjaya uvaca    tam tatha krpayavistam    asru-purnakuleksanam    visidantam idam vakyam    uvaca madhusudanah',N'sanjayah uvaca--Sanjaya said; tam--unto Arjuna; tatha--thus; krpaya--by compassion; avistam--overwhelmed; asru-purna--full of tears; akula--depressed; iksanam--eyes; visidantam--lamenting; idam--this; vakyam--words; uvaca--said; madhu-sudanah--the killer of Madhu.', N'Sanjaya said: Seeing Arjuna full of compassion and very sorrowful, his eyes brimming with tears, Madhusudana, Krsna, spoke the following words.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 2, N'sri-bhagavan uvaca    kutas tva kasmalam idam    visame samupasthitam    anarya-justam asvargyam    akirti-karam arjuna',N'sri-bhagavan uvaca--the Supreme Personality of Godhead said; kutah--wherefrom; tva--unto you; kasmalam--dirtiness; idam--this lamentation;visame--in this hour of crisis; samupasthitam--arrived; anarya--persons who do not know the value of life; justam--practiced by; asvargyam--that which does not lead to higher planets; akirti--infamy; karam--the cause of; arjuna--O Arjuna.', N'The Supreme Person [Bhagavan] said: My dear Arjuna, how have these impurities come upon you? They are not at all befitting a man who knows the progressive values of life. They lead not to higher planets, but to infamy.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 3, N'klaibyam ma sma gamah partha    naitat tvayy upapadyate    ksudram hrdaya-daurbalyam    tyaktvottistha parantapa', N'klaibyam--impotence; ma--do not; sma--take it; gamah--go in; partha--Oson of Prtha; na--never; etat--like this; tvayi--unto you; upadyate--isbefitting; ksudram--very little; hrdaya--heart; daurbalyam--weakness; tyaktva--giving up; uttistha--get up; param-tapa--O chastiser of theenemies. ', N'O son of Prtha, do not yield to this degrading impotence. It does not become you. Give up such petty weakness of heart and arise, O chastiser of the enemy.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 4, N'arjuna uvaca    katham bhismam aham sankhye    dronam ca madhusudana    isubhih pratiyotsyami    pujarhav ari-sudana', N'arjunah uvaca--Arjuna said; katham--how; bhismam--unto Bhisma; aham--I;sankhye--in the fight; dronam--unto Drona; ca--also; madhu-sudana--O killer of Madhu; isubhih--with arrows; pratiyotsyami--shallcounterattack; puja-arhau--those who are worshipable; ari-sudana--O killer of the enemies.', N'Arjuna said: O killer of Madhu [Krsna], how can I counterattack with arrows in battle men like Bhisma and Drona, who are worthy of my worship?');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 5, N'gurun ahatva hi mahanubhavan    sreyo bhoktum bhaiksyam apiha loke    hatvartha-kamams tu gurun ihaiva    bhunjiya bhogan rudhira-pradigdhan', N'gurun--the superiors; ahatva--not killing; hi--certainly; mahaanubhavan--great souls; sreyah--it is better; bhoktum--to enjoy life; bhaiksyam--begging; api--even; iha--in this life; loke--in this world;hatva--killing; artha--gain; kaman--so desiring; tu--but; gurun-- superiors; iha--in this world; eva--certainly; bhunjiya--has to enjoy; bhogan--enjoyable things; rudhira--blood; pradigdhan--tainted with.', N'It is better to live in this world by begging than to live at the cost of the lives of great souls who are my teachers. Even though they are avaricious, they are nonetheless superiors. If they are killed, our spoils will be tainted with blood.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 6, N'na caitad vidmah kataran no gariyo    yad va jayema yadi va no jayeyuh    yan eva hatva na jijivisamas    te vasthitah pramukhe dhartarastrah', N'na--nor; ca--also; etat--this; vidmah--do know; katarat--which; nah--us; gariyah--better; yat--what; va--either; jayema--conquer us; yadi-- if; va--or; nah--us; jayeyuh--conquer; yan--those; eva--certainly;hatva--by killing; na--never; jijivisamah--want to live; te--all of them; avasthitah--are situated; pramukhe--in the front; dhartarastrah--the sons of Dhrtarastra.', N'Nor do we know which is better--conquering them or being conquered by them. The sons of Dhrtarastra, whom if we kill we should not care to live, are now standing before us on this battlefield.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 7, N'karpanya-dosopahata-svabhavah    prcchami tvam dharma-sammudha-cetah    yac chreyah syan niscitam bruhi tan me    sisyas te ham sadhi mam tvam prapannam', N'karpanya--miserly; dosa--weakness; upahata--being inflicted by; svabhavah--characteristics; prcchami--I am asking; tvam--unto You; dharma- -religion; sammudha--bewildered; cetah--in heart; yat--what; sreyah--all-good; syat--may be; niscitam--confidently; bruhi--tell; tat--that; me--unto me; sisyah--disciple; te--Your; aham--I am; sadhi--just instruct; mam--me; tvam--unto You; prapannam--surrendered.', N'Now I am confused about my duty and have lost all composure because of weakness. In this condition I am asking You to tell me clearly what is best for me. Now I am Your disciple, and a soul surrendered unto You. Please instruct me.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 8, N'na hi prapasyami mamapanudyad    yac chokam ucchosanam indriyanam    avapya bhumav asapatnam rddham    rajyam suranam api cadhipatyam', N'na--do not; hi--certainly; prapasyami--I see; mama--my; apanudyat--candrive away; yat--that; sokam--lamentation; ucchosanam--drying up; indriyanam--of the senses; avapya--achieving; bhumau--on the earth;asapatnam--without rival; rddham--prosperous; rajyam--kingdom; suranam- -of the demigods; api--even; ca--also; adhipatyam--supremacy.', N'I can find no means to drive away this grief which is drying up my senses. I will not be able to destroy it even if I win an unrivaled kingdom on earth with sovereignty like the demigods in heaven.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 9, N'sanjaya uvaca    evam uktva hrsikesam    gudakesah parantapah    na yotsya iti govindam    uktva tusnim babhuva ha', N'sanjayah uvaca--Sanjaya said; evam--thus; uktva--speaking; hrsikesam--unto Krsna, the master of the senses; gudakesah--Arjuna, the master at curbing ignorance; parantapah--the chastiser of the enemies; na yotsye--I shall not fight; iti--thus; govindam--unto Krsna, the giver of pleasure; uktva--saying; tusnim--silent; babhuva--became; ha--certainly.', N'Sanjaya said: Having spoken thus, Arjuna, chastiser of enemies, told Krsna, "Govinda, I shall not fight," and fell silent. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 10, N'tam uvaca hrsikesah    prahasann iva bharata    senayor ubhayor madhye    visidantam, idam vacah', N'tam--unto him; uvaca--said; hrsikesah--the master of the senses, Krsna;prahasan--smiling; iva--like that; bharata--O Dhrtarastra, descendant of Bharata; senayoh--of the armies; ubhayoh--of both parties; madhye--between; visidantam--unto the lamenting one; idam--the following; vacah--words.', N'O descendant of Bharata, at that time Krsna, smiling, in the midst of both the armies, spoke the following words to the grief-stricken Arjuna.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 11, N'sri-bhagavan uvaca    asocyan anvasocas tvam    prajna-vadams ca bhasase    gatasun agatasums ca    nanusocanti panditah', N'sri-bhagavan uvaca--the Supreme Personality of Godhead said; asocyan--that which is not worthy of lamentation; anvasocah--you are lamenting; tvam--you; prajna-vadan--learned talks; ca--also; bhasase--speaking;gata--lost; asun--life; agata--not past; asun--life; ca--also; na-- never; anusocanti--lament; panditah--the learned.', N'The Blessed Lord said: While speaking learned words, you are mourning for what is not worthy of grief. Those who are wise lament neither for the living nor the dead.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 12, N'na tv evaham jatu nasam    na tvam neme janadhipah    na caiva na bhavisyamah    sarve vayam atah param', N'na--never; tu--but; eva--certainly; aham--I; jatu--become; na--never;asam--existed; na--it is not so; tvam--yourself; na--not; ime--all these; jana-adhipah--kings; na--never; ca--also; eva--certainly; na--not like that; bhavisyamah--shall exist; sarve--all of us; vayam--we; atah param--hereafter.', N'Never was there a time when I did not exist, nor you, nor all these kings; nor in the future shall any of us cease to be. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 13, N'dehino smin yatha dehe    kaumaram yauvanam jara    tatha dehantara-praptir    dhiras tatra na muhyati', N'dehinah--of the embodied; asmin--in this; yatha--as; dehe--in the body;kaumaram--boyhood; yauvanam--youth; jara--old age; tatha--similarly; deha-antara--transference of the body; praptih--achievement; dhirah--the sober; tatra--thereupon; na--never; muhyati--deluded. ', N'As the embodied soul continuously passes, in this body, from boyhood to youth to old age, the soul similarly passes into another body at death. A self-realized soul is not bewildered by such a change.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 14, N'matra-sparsas tu kaunteya    sitosna-sukha-duhkha-dah    agamapayino nityas    tams titiksasva bharata', N'matra--sensuous; sparsah--perception; tu--only; kaunteya--O son ofKunti; sita--winter; usna--summer; sukha--happiness; duhkha-dah--giving pain; agama--appearing; apayinah--disappearing; anityah--nonpermanent;tan--all of them; titiksasva--just try to tolerate; bharata--O descendant of the Bharata dynasty.', N'O son of Kunti, the nonpermanent appearance of happiness and distress, and their disappearance in due course, are like the appearance and disappearance of winter and summer seasons. They arise from sense perception, O scion of Bharata, and one must learn to tolerate them without being disturbed.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 15, N'yam hi na vyathayanty ete    purusam purusarsabha    sama-duhkha-sukham dhiram    so mrtatvaya kalpate', N'yam--one whom; hi--certainly; na--never; vyathayanti--are distressing;ete--all these; purusam--to a person; purusa-rsabha--O best among men; sama--unaltered; duhkha--distressed; sukham--happiness; dhiram--patient; sah--he; amrtatvaya--for liberation; kalpate--is considered eligible.', N'O best among men [Arjuna], the person who is not disturbed by happiness and distress and is steady in both is certainly eligible for liberation.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 16, N'nasato vidyate bhavo    nabhavo vidyate satah    ubhayor api drsto ntas    tv anayos tattva-darsibhih', N'na--never; asatah--of the nonexistent; vidyate--there is; bhavah--endurance; na--never; abhavah--changing quality; vidyate--there is; satah--of the eternal; ubhayoh--of the two; api--verily; drstah--observed; antah--conclusion; tu--but; anayoh--of them; tattva--truth; darsibhih--by the seers.', N'Those who are seers of the truth have concluded that of the nonexistent there is no endurance, and of the existent there is no cessation. This seers have concluded by studying the nature of both.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 17, N'avinasi tu tad viddhi    yena sarvam idam tatam    vinasam avyayasyasya    na kascit kartum arhati', N'avinasi--imperishable; tu--but; tat--that; viddhi--know it; yena--bywhom; sarvam--all of the body; idam--this; tatam--pervaded; vinasam-- destruction; avyayasya--of the imperishable; asya--of it; na kascit--noone; kartum--to do; arhati--is able. ', N'Know that which pervades the entire body is indestructible. No one is able to destroy the imperishable soul. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 18, N'antavanta ime deha    nityasyoktah saririnah    anasino prameyasya    tasmad yudhyasva bharata', N'anta-vantah--perishable; ime--all these; dehah--material bodies;nityasya--eternal in existence; uktah--it is so said; saririnah--the embodied soul; anasinah--never to be destroyed; aprameyasya--immeasurable; tasmat--therefore; yudhyasva--fight; bharata--O descendant of Bharata.', N'Only the material body of the indestructible, immeasurable and eternal living entity is subject to destruction; therefore, fight, O descendant of Bharata.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 19, N'ya enam vetti hantaram    yas cainam manyate hatam    ubhau tau na vijanito    nayam hanti na hanyate', N'yah--anyone; enam--this; vetti--knows; hantaram--the killer; yah--anyone; ca--also; enam--this; manyate--thinks; hatam--killed; ubhau-- both of them; tau--they; na--never; vijanitah--in knowledge; na--never;ayam--this; hanti--kills; na--nor; hanyate--be killed. ', N'He who thinks that the living entity is the slayer or that he is slain, does not understand. One who is in knowledge knows that the self slays not nor is slain.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 20, N'na jayate mriyate va kadacin    nayam bhutva bhavita va na bhuyah    ajo nityah sasvato yam purano    na hanyate hanyamane sarire', N'na--never; jayate--takes birth; mriyate--never dies; va--either;kadacit--at any time (past, present or future); na--never; ayam--this; bhutva--came into being; bhavita--will come to be; va--or; na--not;bhuyah--or has coming to be; ajah--unborn; nityah--eternal; sasvatah-- permanent; ayam--this; puranah--the oldest; na--never; hanyate--is killed; hanyamane--being killed; sarire--by the body.', N'For the soul there is never birth nor death. Nor, having once been, does He ever cease to be. He is unborn, eternal, ever-existing, undying and primeval. He is not slain when the body is slain.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 21, N'vedavinasinam nityam    ya enam ajam avyayam    katham sa purusah partha    kam ghatayati hanti kam', N'veda--in knowledge; avinasinam--indestructible; nityam--always; yah--one who; enam--this (soul); ajam--unborn; avyayam--immutable; katham-- how; sah--he; purusah--person; partha--O Partha (Arjuna); kam--whom;ghatayati--hurts; hanti--kills; kam--whom. ', N'O Partha, how can a person who knows that the soul is indestructible, unborn, eternal and immutable, kill anyone or cause anyone to kill? ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 22, N'vasamsi jirnani yatha vihaya    navani grhnati naro parani    tatha sarirani vihaya jirnany    anyani samyati navani dehi', N'vasamsi--garments; jirnani--old and worn out; yatha--as it is; vihaya--giving up; navani--new garments; grhnati--does accept; narah--a man; aparani--other; tatha--in the same way; sarirani--bodies; vihaya--giving up; jirnani--old and useless; anyani--different; samyati--verily accepts; navani--new sets; dehi--the embodied.', N'As a person puts on new garments, giving up old ones, similarly, the soul accepts new material bodies, giving up the old and useless ones. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 23, N'nainam chindanti sastrani    nainam dahati pavakah    na cainam kledayanty apo    na sosayati marutah', N'na--never; enam--this soul; chindanti--can cut to pieces; sastrani--allweapons; na--never; enam--unto this soul; dahati--burns; pavakah--fire; na--never; ca--also; enam--unto this soul; kledayanti--moistens; apah--water; na--never; sosayati--dries; marutah--wind. ', N'The soul can never be cut to pieces by any weapon, nor burned by fire, nor moistened by water, nor withered by the wind. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 24, N'acchedyo yam adahyo yam    akledyo sosya eva ca    nityah sarva-gatah sthanur    acalo yam sanatanah', N'acchedyah--unbreakable; ayam--this soul; adahyah--cannot be burned;ayam--this soul; akledyah--insoluble; asosyah--cannot be dried; eva-- certainly; ca--and; nityah--everlasting; sarva-gatah--all-pervading;sthanuh--unchangeable; acalah--immovable; ayam--this soul; sanatanah-- eternally the same.', N'This individual soul is unbreakable and insoluble, and can be neither burned nor dried. He is everlasting, all-pervading, unchangeable, immovable and eternally the same.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 25, N'avyakto yam acintyo yam    avikaryo yam ucyate    tasmad evam viditvainam    nanusocitum arhasi', N'avyaktah--invisible; ayam--this soul; acintyah--inconceivable; ayam--this soul; avikaryah--unchangeable; ayam--this soul; ucyate--is said; tasmat--therefore; evam--like this; viditva--knowing it well; enam--this soul; na--do not; anusocitum--may lament over; arhasi--you deserve.', N'It is said that the soul is invisible, inconceivable, immutable, and unchangeable. Knowing this, you should not grieve for the body. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 26, N'atha cainam nitya-jatam    nityam va manyase mrtam    tathapi tvam maha-baho    nainam socitum arhasi', N'atha--if, however; ca--also; enam--this soul; nitya-jatam--always born;nityam--forever; va--either; manyase--so think; mrtam--dead; tatha api- -still; tvam--you; maha-baho--O mighty-armed one; na--never; enam--about the soul; socitum--to lament; arhasi--deserve. ', N'If, however, you think that the soul is perpetually born and always dies still, you still have no reason to lament, O mighty-armed. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 27, N'jatasya hi dhruvo mrtyur    dhruvam janma mrtasya ca    tasmad apariharye rthe    na tvam socitum arhasi', N'jatasya--one who has taken his birth; hi--certainly; dhruvah--a fact;mrtyuh--death; dhruvam--it is also a fact; janma--birth; mrtasya--of the dead; ca--also; tasmat--therefore; apariharye--for that which isunavoidable; arthe--in the matter of; na--do not; tvam--you; socitum-- to lament; arhasi--deserve.', N'For one who has taken his birth, death if certain; and for one who is dead, birth is certain. Therefore, in the unavoidable discharge of your duty, you should not lament.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 28, N'avyaktadini bhutani    vyakta-madhyani bharata    avyakta-nidhanany eva    tatra ka paridevana', N'avyakta-adini--in the beginning unmanifested; bhutani--all that arecreated; vyakta--manifested; madhyani--in the middle; bharata--O descendant of Bharata; avyakta--nonmanifested; nidhanani--all that arevanquished; eva--it is all like that; tatra--therefore; ka--what; paridevana--lamentation.', N'All created beings are unmanifest in their beginning, manifest in their interim state, and unmanifest again when they are annihilated. So what need is there for lamentation?');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 29, N'ascarya-vat pasyati kascid enam    ascarya-vad vadati tathaiva canyah    ascarya-vac cainam anyah srnoti    srutvapy enam veda na caiva kascit', N'ascarya-vat--amazing; pasyati--see; kascit--some; enam--this soul;ascarya-vat--amazing; vadati--speak; tatha--there; eva--certainly; ca-- also; anyah--another; ascarya-vat--similarly amazing; ca--also; enam--this soul; anyah--others; srnoti--hear; srutva--having heard; api-- even; enam--this soul; veda--do know; na--never; ca--and; eva--certainly; kascit--anyone.', N'Some look at the soul as amazing, some describe him as amazing, and some hear of him as amazing, while others, even after hearing about him, cannot understand him at all.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 30, N'dehi nityam avadhyo yam    dehe sarvasya bharata    tasmat sarvani bhutani    na tvam socitum arhasi', N'dehi--the owner of the material body; nityam--eternally; avadhyah--cannot be killed; ayam--this soul; dehe--in the body; sarvasya--of everyone; bharata--O descendant of Bharata; tasmat--therefore; sarvani--all; bhutani--living entities (that are born); na--never; tvam-- yourself; socitum--to lament; arhasi--deserve.', N'O descendant of Bharata, he who dwells in the body is eternal and can never be slain. Therefore you need not grieve for any creature. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 31, N'sva-dharmam api caveksya    na vikampitum arhasi    dharmyad dhi yuddhac chreyo nyat    ksatriyasya na vidyate', N'sva-dharmam--one own religious principles; api--also; ca--indeed;aveksya--considering; na--never; vikampitum--to hesitate; arhasi--you deserve; dharmyat--from religious principles; hi--indeed; yuddhat--thanfighting; sreyah--better engagements; anyat--anything else; ksatriyasya--of the ksatriya; na--does not; vidyate--exist.', N'Considering your specific duty as a ksatriya, you should know that there is no better engagement for you than fighting on religious principles; and so there is no need for hesitation.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 32, N'yadrcchaya copapannam    svarga-dvaram apavrtam    sukhinah ksatriyah partha    labhante yuddham idrsam', N'yadrcchaya--by its own accord; ca--also; upapannam--arrived at; svarga--heavenly planet; dvaram--door; apavrtam--wide open; sukhinah--very happy; ksatriyah--the members of the royal order; partha--O son ofPrtha; labhante--do achieve; yuddham--war; idrsam--like this. ', N'O Partha, happy are the ksatriyas to whom such fighting opportunities come unsought, opening for them the doors of the heavenly planets. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 33, N'atha cet tvam imam dharmyam    sangramam na karisyasi    tatah sva-dharmam kirtim ca    hitva papam avapsyasi', N'atha--therefore; cet--if; tvam--you; imam--this; dharmyam--religiousduty; sangramam--fighting; na--do not; karisyasi--perform; tatah--then; sva-dharmam--your religious duty; kirtim--reputation; ca--also; hitva--losing; papam--sinful reaction; avapsyasi--do gain. ', N'If, however, you do not fight this religious war, then you will certainly incur sins for neglecting your duties and thus lose your reputation as a fighter.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 34, N'akirtim capi bhutani    kathayisyanti te vyayam    sambhavitasya cakirtir    maranad atiricyate', N'akirtim--infamy; ca--also; api--over and above; bhutani--all people;kathayisyanti--will speak; te--of you; avyayam--forever; sambhavitasya- -for a respectable man; ca--also; akirtih--ill fame; maranat--thandeath; atiricyate--becomes more than. ', N'People will always speak of your infamy, and for one who has been honored, dishonor is worse than death. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 35, N'bhayad ranad uparatam    mamsyante tvam maha-rathah    yesam ca tvam bahu-mato    bhutva yasyasi laghavam', N'bhayat--out of fear; ranat--from the battlefield; uparatam--ceased;mamsyante--will consider; tvam--unto you; maha-rathah--the great generals; yesam--of those who; ca--also; tvam--you; bahu-matah--ingreat estimation; bhutva--will become; yasyasi--will go; laghavam-- decreased in value.', N'The great generals who have highly esteemed your name and fame will think that you have left the battlefield out of fear only, and thus they will consider you a coward.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 36, N'avacya-vadams ca bahun    vadisyanti tavahitah    nindantas tava samarthyam    tato duhkhataram nu kim', N'avacya--unkind; vadan--fabricated words; ca--also; bahun--many;vadisyanti--will say; tava--your; ahitah--enemies; nindantah--while vilifying; tava--your; samarthyam--ability; tatah--thereafter; duhkhataram--more painful; nu--of course; kim--what is there. ', N'Your enemies will describe you in many unkind words and scorn your ability. What could be more painful for you? ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 37, N'hato va prapsyasi svargam    jitva va bhoksyase mahim    tasmad uttistha kaunteya    yuddhaya krta-niscayah', N'hatah--being killed; va--either; prapsyasi--you will gain; svargam--theheavenly kingdom; jitva--by conquering; va--or; bhoksyase--you enjoy; mahim--the world; tasmat--therefore; uttistha--get up; kaunteya--O sonof Kunti; yuddhaya--to fight; krta--determined; niscayah--uncertainty. ', N'O son of Kunti, either you will be killed on the battlefield and attain the heavenly planets, or you will conquer and enjoy the earthly kingdom. Therefore get up and fight with determination.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 38, N'sukha-duhkhe same krtva    labhalabhau jayajayau    tato yuddhaya yujyasva    naivam papam avapsyasi', N'sukha--happiness; duhkhe--in distress; same--in equanimity; krtva--doing so; labha-alabhau--both in loss and profit; jaya-ajayau--both in defeat and victory; tatah--thereafter; yuddhaya--for the sake offighting; yujyasva--do fight; na--never; evam--in this way; papam-- sinful reaction; avapsyasi--you will gain.', N'Do thou fight for the sake of fighting, without considering happiness or distress, loss or gain, victory or defeat--and, by so doing, you shall never incur sin.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 39, N'esa te bhihita sankhye    buddhir yoge tv imam srnu    buddhya yukto yaya partha    karma-bandham prahasyasi', N'esa--all these; te--unto you; abhihita--described; sankhye--byanalytical study; buddhih--intelligence; yoge--work without fruitive result; tu--but; imam--this; srnu--just hear; buddhya--by intelligence;yuktah--dovetailed; yaya--by which; partha--O son of Prtha; karmabandham-- bondage of reaction; prahasyasi--you can be released from.', N'Thus far I have declared to you the analytical knowledge of sankhya philosophy. Now listen to the knowledge of yoga whereby one works without fruitive result. O son of Prtha, when you act by such intelligence, you can free yourself from the bondage of works.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 40, N'nehabhikrama-naso sti    pratyavayo na vidyate    sv-alpam apy asya dharmasya    trayate mahato bhayat', N'na--there is not; iha--in this world; abhikrama--endeavoring; nasah--loss; asti--there is; pratyavayah--diminution; na--never; vidyate-- there is; su-alpam--a little; api--although; asya--of this; dharmasya--of this occupation; trayate--releases; mahatah--of very great; bhayat-- danger.', N'In this endeavor there is no loss or diminution, and a little advancement on this path can protect one from the most dangerous type of fear.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 41, N'vyavasayatmika buddhir    ekeha kuru-nandana    bahu-sakha hy anantas ca    buddhayo vyavasayinam', N'vyavasaya-atmika--resolute Krsna consciousness; buddhih--intelligence;eka--only one; iha--in this world; kuru-nandana--O beloved child of the Kurus; bahu-sakhah--various branches; hi--indeed; anantah--unlimited;ca--also; buddhayah--intelligence; avyavasayinam--of those who are not in Krsna consciousness.', N'Those who are on this path are resolute in purpose, and their aim is one. O beloved child of the Kurus, the intelligence of those who are irresolute is many-branched.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 44, N'bhogaisvarya-prasaktanam    tayapahrta-cetasam    vyavasayatmika buddhih    samadhau na vidhiyate', N'bhoga--material enjoyment; aisvarya--opulence; prasaktanam--those whoare so attached; taya--by such things; apahrta-cetasam--bewildered in mind; vyavasaya-atmika--fixed determination; buddhih--devotionalservice of the Lord; samadhau--in the controlled mind; na--never; vidhiyate--does take place.', N'In the minds of those who are too attached to sense enjoyment and material opulence, and who are bewildered by such things, the resolute determination of devotional service to the Supreme Lord does not take place.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 45, N'trai-gunya-visaya veda    nistrai-gunyo bhavarjuna    nirdvandvo nitya-sattva-stho    niryoga-ksema atmavan', N'trai-gunya--pertaining to the three modes of material nature; visayah--on the subject matter; vedah--Vedic literatures; nistrai-gunyah--in a pure state of spiritual existence; bhava--be; arjuna--O Arjuna;nirdvandvah--free from the pains of opposites; nitya-sattva-sthah--ever remaining in sattva (goodness); niryoga-ksemah--free from (the thought of) acquisition and preservation; atma-van--established in the self.', N'The Vedas mainly deal with the subject of the three modes of material nature. Rise above these modes, O Arjuna. Be transcendental to all of them. Be free from all dualities and from all anxieties for gain and safety, and be established in the self.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 46, N'yavan artha udapane    sarvatah samplutodake    tavan sarvesu vedesu    brahmanasya vijanatah', N'yavan--all that; arthah--is meant; uda-pane--in a well of water;sarvatah--in all respects; sampluta-udake--in a great reservoir of water; tavan--similarly; sarvesu--in all; vedesu--Vedic literatures;brahmanasya--of the man who knows the Supreme Brahman; vijanatah--of one who is in complete knowledge.', N'All purposes that are served by the small pond can at once be served by the great reservoirs of water. Similarly, all the purposes of the Vedas can be served to one who knows the purpose behind them.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 47, N'karmany evadhikaras te    ma phalesu kadacana    ma karma-phala-hetur bhur    ma te sango stv akarmani', N'karmani--prescribed duties; eva--certainly; adhikarah--right; te--ofyou; ma--never; phalesu--in the fruits; kadacana--at any time; ma-- never; karma-phala--in the result of the work; hetuh--cause; bhuh--become; ma--never; te--of you; sangah--attachment; astu--be there; akarmani--in not doing.', N'You have a right to perform your prescribed duty, but you are not entitled to the fruits of action. Never consider yourself to be the cause of the results of your activities, and never be attached to not doing your duty.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 48, N'yoga-sthah kuru karmani    sangam tyaktva dhananjaya    siddhy-asiddhyoh samo bhutva    samatvam yoga ucyate', N'yoga-sthah--steadfast in yoga; kuru--perform; karmani--your duties;sangam--attachment; tyaktva--having abandoned; dhananjaya--O Dhananjaya; siddhi-asiddhyoh--success and failure; samah--the same;bhutva--having become; samatvam--evenness of mind; yogah--yoga; ucyate- -is called.', N'Be steadfast in yoga, O Arjuna. Perform your duty and abandon all attachment to success or failure. Such evenness of mind is called yoga. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 49, N'durena hy avaram karma    buddhi-yogad dhananjaya    buddhau saranam anviccha    krpanah phala-hetavah', N'durena--by discarding it at a long distance; hi--certainly; avaram--abominable; karma--activities; buddhi-yogat--on the strength of Krsna consciousness; dhananjaya--O conqueror of wealth; buddhau--in suchconsciousness; saranam--full surrender; anviccha--desire; krpanah--the misers; phala-hetavah--those desiring fruitive action.', N'O Dhananjaya, rid yourself of all fruitive activities by devotional service, and surrender fully to that consciousness. Those who want to enjoy the fruits of their work are misers.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 50, N'buddhi-yukto jahatiha    ubhe sukrta-duskrte    tasmad yogaya yujyasva    yogah karmasu kausalam', N'buddhi-yuktah--one who is engaged in devotional service; jahati--canget rid of; iha--in this life; ubhe--in both; sukrta-duskrte--in good and bad results; tasmat--therefore; yogaya--for the sake of devotionalservice; yujyasva--be so engaged; yogah--Krsna consciousness; karmasu-- in all activities; kausalam--art.', N'A man engaged in devotional service rids himself of both good and bad actions even in this life. Therefore strive for yoga, O Arjuna, which is the art of all work.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 51, N'karma-jam buddhi-yukta hi    phalam tyaktva manisinah    janma-bandha-vinirmuktah    padam gacchanty anamayam', N'karma-jam--because of fruitive activities; buddhi-yuktah--being done indevotional service; hi--certainly; phalam--results; tyaktva--giving up; manisinah--devotees who are great sages; janma-bandha--the bondage ofbirth and death; vinirmuktah--liberated soul; padam--position; gacchanti--reached; anamayam--without miseries.', N'The wise, engaged in devotional service, take refuge in the Lord, and free themselves from the cycle of birth and death by renouncing the fruits of action in the material world. In this way they can attain that state beyond all miseries.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 52, N'yada te moha-kalilam    buddhir vyatitarisyati    tada gantasi nirvedam    srotavyasya srutasya ca', N'yada--when; te--your; moha--illusory; kalilam--dense forest; buddhih--transcendental service with intelligence; vyatitarisyati--surpasses; tada--at that time; ganta asi--you shall go; nirvedam--callousness;srotavyasya--all that is to be heard; srutasya--all that is already heard; ca--also.', N'When your intelligence has passed out of the dense forest of delusion, you shall become indifferent to all that has been heard and all that is to be heard.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 53, N'sruti-vipratipanna te    yada sthasyati niscala    samadhav acala buddhis    tada yogam avapsyasi', N'sruti--Vedic revelation; vipratipanna--without being influenced by thefruitive results of the Vedas; te--your; yada--when; sthasyati-- remains; niscala--unmoved; samadhau--in transcendental consciousness,or Krsna consciousness; acala--unflinching; buddhih--intelligence; tada--at that time; yogam--self-realization; avapsyasi--you will achieve.', N'When your mind is no longer disturbed by the flowery language of the Vedas, and when it remains fixed in the trance of self-realization, then you will have attained the divine consciousness.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 54, N'arjuna uvaca    sthita-prajnasya ka bhasa    samadhi-sthasya kesava    sthita-dhih kim prabhaseta    kim asita vrajeta kim', N'arjunah uvaca--Arjuna said; sthita-prajnasya--of one who is situated infixed Krsna consciousness; ka--what; bhasa--language; samadhi-sthasya-- of one situated in trance; kesava--O Krsna; sthita-dhih--one fixed inKrsna consciousness; kim--what; prabhaseta--speak; kim--how; asita-- does remain; vrajeta--walks; kim--how.', N'Arjuna said: O Krsna, what are the symptoms of one whose consciousness is thus merged in transcendence? How does he speak, and what is his language? How does he sit, and how does he walk?');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 55, N'sri-bhagavan uvaca    prajahati yada kaman    sarvan partha mano-gatan    atmany evatmana tustah    sthita-prajnas tadocyate', N'sri-bhagavan uvaca--the Supreme Personality of Godhead said; prajahati--gives up; yada--when; kaman--desires for sense gratification; sarvan-- of all varieties; partha--O son of Prtha; manah-gatan--of mentalconcoction; atmani--in the pure state of the soul; eva--certainly; atmana--by the purified mind; tustah--satisfied; sthita-prajnah--transcendentally situated; tada--at that time; ucyate--is said.', N'The Blessed Lord said: O Partha, when a man gives up all varieties of sense desire which arise from mental concoction, and when his mind finds satisfaction in the self alone, then he is said to be in pure transcendental consciousness.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 56, N'duhkhesv anudvigna-manah    sukhesu vigata-sprhah    vita-raga-bhaya-krodhah    sthita-dhir munir ucyate', N'duhkhesu--in the threefold miseries; anudvigna-manah--without beingagitated in mind; sukhesu--in happiness; vigata-sprhah--without being too interested; vita--free from; raga--attachment; bhaya--fear;krodhah--anger; sthita-dhih--one who is steady; munih--a sage; ucyate-- is called.', N'One who is not disturbed in spite of the threefold miseries, who is not elated when there is happiness, and who is free from attachment, fear and anger, is called a sage of steady mind.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 57, N'yah sarvatranabhisnehas    tat tat prapya subhasubham    nabhinandati na dvesti    tasya prajna pratisthita', N'yah--one who; sarvatra--everywhere; anabhisnehah--without affection;tat--that; tat--that; prapya--achieving; subha--good; asubham--evil; na--never; abhinandati--praise; na--never; dvesti--envies; tasya--his;prajna--perfect knowledge; pratisthita--fixed. ', N'He who is without attachment, who does not rejoice when he obtains good, nor lament when he obtains evil, is firmly fixed in perfect knowledge.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 58, N'yada samharate cayam    kurmo nganiva sarvasah    indriyanindriyarthebhyas    tasya prajna pratisthita', N'yada--when; samharate--winds up; ca--also; ayam--all these; kurmah--tortoise; angani--limbs; iva--like; sarvasah--altogether; indriyani-- senses; indriya-arthebhyah--from the sense objects; tasya--his; prajna--consciousness; pratisthita--fixed up. ', N'One who is able to withdraw his senses from sense objects, as the tortoise draws its limbs within the shell, is to be understood as truly situated in knowledge.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 59, N'visaya vinivartante    niraharasya dehinah    rasa-varjam raso py asya    param drstva nivartate', N'visayah--objects for sense enjoyment; vinivartante--are practiced to berefrained from; niraharasya--by negative restrictions; dehinah--for the embodied; rasa-varjam--giving up the taste; rasah--sense of enjoyment;api--although there is; asya--his; param--far superior things; drstva-- by experiencing; nivartate--ceases from.', N'The embodied soul may be restricted from sense enjoyment, though the taste for sense objects remains. But, ceasing such engagements by experiencing a higher taste, he is fixed in consciousness.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 60, N'yatato hy api kaunteya    purusasya vipascitah    indriyani pramathini    haranti prasabham manah', N'yatatah--while endeavoring; hi--certainly; api--in spite of; kaunteya--O son of Kunti; purusasya--of the man; vipascitah--full of discriminating knowledge; indriyani--the senses; pramathini--stimulated; haranti--throws forcefully; prasabham--by force; manah--the mind.', N'The senses are so strong and impetuous, O Arjuna, that they forcibly carry away the mind even of a man of discrimination who is endeavoring to control them.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 61, N'tani sarvani samyamya    yukta asita mat-parah    vase hi yasyendriyani    tasya prajna pratisthita', N'tani--those senses; sarvani--all; samyamya--keeping under control;yuktah--being engaged; asita--being so situated; mat-parah--in relationship with Me; vase--in full subjugation; hi--certainly; yasya--one whose; indriyani--senses; tasya--his; prajna--consciousness; pratisthita--fixed.', N'One who restrains his senses and fixes his consciousness upon Me, is known as a man of steady intelligence. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 62, N'dhyayato visayan pumsah    sangas tesupajayate    sangat sanjayate kamah    kamat krodho bhijayate', N'dhyayatah--while contemplating; visayan--sense objects; pumsah--of theperson; sangah--attachment; tesu--in the sense objects; upajayate-- develops; sangat--attachment; sanjayate--develops; kamah--desire;kamat--from desire; krodhah--anger; abhijayate--becomes manifest. ', N'While contemplating the objects of the senses, a person develops attachment for them, and from such attachment lust develops, and from lust anger arises.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 63, N'krodhad bhavati sammohah    sammohat smrti-vibhramah    smrti-bhramsad buddhi-naso    buddhi-nasat pranasyati', N'krodhat--from anger; bhavati--takes place; sammohah--perfect illusion;sammohat--from illusion; smrti--of memory; vibhramah--bewilderment; smrti-bhramsat--after bewilderment of memory; buddhi-nasah--loss ofintelligence; buddhi-nasat--and from loss of intelligence; pranasyati-- falls down.', N'From anger, delusion arises, and from delusion bewilderment of memory. When the memory is bewildered, intelligence is lost, and when intelligence is lost, one falls down again into the material pool.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 64, N'raga-dvesa-vimuktais tu    visayan indriyais caran    atma-vasyair vidheyatma    prasadam adhigacchati', N'raga--attachment; dvesa--detachment; vimuktaih--by one who has beenfree from such things; tu--but; visayan--sense objects; indriyaih--by the senses; caran--acting; atma-vasyaih--one who has control over;vidheya-atma--one who follows regulated freedom; prasadam--the mercy of the Lord; adhigacchati--attains.', N'One who can control his senses by practicing the regulative principles of freedom can obtain the complete mercy of the Lord and thus become free from all attachment and aversion.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 65, N'prasade sarva-duhkhanam    hanir asyopajayate    prasanna-cetaso hy asu    buddhih paryavatisthate', N'prasade--on achievement of the causeless mercy of the Lord; sarva--ofall; duhkhanam--material miseries; hanih--destruction; asya--his; upajayate--takes place; prasanna-cetasah--of the happy-minded; hi--certainly; asu--very soon; buddhih--intelligence; pari--sufficiently; avatisthate--established.', N'For one who is so situated in the Divine consciousness, the threefold miseries of material existence exist no longer; in such a happy state, one intelligence soon becomes steady.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 66, N'nasti buddhir ayuktasya    na cayuktasya bhavana    na cabhavayatah santir    asantasya kutah sukham', N'na asti--there cannot be; buddhih--transcendental intelligence;ayuktasya--of one who is not connected (with Krsna consciousness); na-- neither; ca--and; ayuktasya--of one devoid of Krsna consciousness;bhavana--mind fixed in happiness; na--neither; ca--and; abhavayatah-- one who is not fixed; santih--peace; asantasya--of the unpeaceful;kutah--where is; sukham--happiness.', N'One who is not in transcendental consciousness can have neither a controlled mind nor steady intelligence, without which there is no possibility of peace. And how can there be any happiness without peace?');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 67, N'indriyanam hi caratam    yan mano nuvidhiyate    tad asya harati prajnam    vayur navam ivambhasi', N'indriyanam--of the senses; hi--certainly; caratam--while herding over;yat--that; manah--mind; anuvidhiyate--becomes constantly engaged; tat-- that; asya--his; harati--takes away; prajnam--intelligence; vayuh--wind; navam--a boat; iva--like; ambhasi--on the water. ', N'As a boat on the water is swept away by a strong wind, even one of the senses on which the mind focuses can carry away a man intelligence. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 68, N'tasmad yasya maha-baho    nigrhitani sarvasah    indriyanindriyarthebhyas    tasya prajna pratisthita', N'tasmat--therefore; yasya--of one; maha-baho--O mighty-armed one;nigrhitani--so curbed down; sarvasah--all around; indriyani--the senses; indriya-arthebhyah--for the sake of sense objects; tasya--his;prajna--intelligence; pratisthita--fixed. ', N'Therefore, O mighty-armed, one whose senses are restrained from their objects is certainly of steady intelligence. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 69, N'ya nisa sarva-bhutanam    tasyam jagarti samyami    yasyam jagrati bhutani    sa nisa pasyato muneh', N'ya--what; nisa--is night; sarva--all; bhutanam--of living entities;tasyam--in that; jagarti--wakeful; samyami--the self-controlled; yasyam--in which; jagrati--awake; bhutani--all beings; sa--that is;nisa--night; pasyatah--for the introspective; muneh--sage. ', N'What is night for all beings is the time of awakening for the selfcontrolled; and the time of awakening for all beings is night for the introspective sage.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 70, N'apuryamanam acala-pratistham    samudram apah pravisanti yadvat    tadvat kama yam pravisanti sarve    sa santim apnoti na kama-kami', N'apuryamanam--always filled; acala-pratistham--steadily situated;samudram--the ocean; apah--water; pravisanti--enter; yadvat--as; tadvat--so; kamah--desires; yam--unto one; pravisanti--enter; sarve--all; sah--that person; santim--peace; apnoti--achieves; na--not; kamakami-- one who desires to fulfill desires.', N'A person who is not disturbed by the incessant flow of desires--that enter like rivers into the ocean which is ever being filled but is always still--can alone achieve peace, and not the man who strives to satisfy such desires.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 71, N'vihaya kaman yah sarvan    pumams carati nihsprhah    nirmamo nirahankarah    sa santim adhigacchati', N'vihaya--after giving up; kaman--all material desires for sensegratification; yah--the person; sarvan--all; puman--a person; carati-- lives; nihsprhah--desireless; nirmamah--without a sense ofproprietorship; nirahankarah--without false ego; sah--all; santim-- perfect peace; adhigacchati--attains.', N'A person who has given up all desires for sense gratification, who lives free from desires, who has given up all sense of proprietorship and is devoid of false ego--he alone can attain real peace.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 2, 72, N'esa brahmi sthitih partha    nainam prapya vimuhyati    sthitvasyam anta-kale pi    brahma-nirvanam rcchati', N'esa--this; brahmi--spiritual; sthitih--situation; partha--O son ofPrtha; na--never; enam--this; prapya--achieving; vimuhyati--bewilders; sthitva--being so situated; asyam--being so; anta-kale--at the end oflife; api--also; brahma-nirvanam--spiritual (kingdom of God); rcchati-- attains.', N'That is the way of the spiritual and godly life, after attaining which a man is not bewildered. Being so situated even at the hour of death, one can enter into the kingdom of God.');

