INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  1, N'arjuna uvaca    jyayasi cet karmanas te    mata buddhir janardana    tat kim karmani ghore mam    niyojayasi kesava', N'arjunah--Arjuna; uvaca--said; jyayasi--speaking very highly; cet--although; karmanah--than fruitive action; te--Your; mata--opinion; buddhih--intelligence; janardana--O Krsna; tat--therefore; kim--why;karmani--in action; ghore--ghastly; mam--me; niyojayasi--engaging me; kesava--O Krsna.', N'Arjuna said: O Janardana, O Kesava, why do You urge me to engage in this ghastly warfare, if You think that intelligence is better than fruitive work?');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  2, N'vyamisreneva vakyena    buddhim mohayasiva me    tad ekam vada niscitya    yena sreyo ham apnuyam', N'vyamisrena--by equivocal; iva--as; vakyena--words; buddhim--intelligence; mohayasi--bewildering; iva--as; me--my; tat--therefore; ekam--only one; vada--please tell; niscitya--ascertaining; yena--bywhich; sreyah--real benefit; aham--I; apnuyam--may have it. ', N'My intelligence is bewildered by Your equivocal instructions. Therefore, please tell me decisively what is most beneficial for me. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  3, N'sri-bhagavan uvaca    loke smin dvi-vidha nistha    pura prokta mayanagha    jnana-yogena sankhyanam    karma-yogena yoginam', N'sri-bhagavan uvaca--the Supreme Personality of Godhead said; loke--inthe world; asmin--this; dvi-vidha--two kinds of; nistha--faith; pura-- formerly; prokta--were said; maya--by Me; anagha--O sinless one; jnanayogena--by the linking process of knowledge; sankhyanam--of the empiric philosophers; karma-yogena--by the linking process of devotion; yoginam--of the devotees.', N'The Supreme Personality of Godhead said: O sinless Arjuna, I have already explained that there are two classes of men who try to realize the self. Some are inclined to understand Him by empirical, philosophical speculation, and others are inclined to know Him by devotional work.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  4, N'na karmanam anarambhan    naiskarmyam puruso snute    na ca sannyasanad eva    siddhim samadhigacchati', N'na--without; karmanam--of the prescribed duties; anarambhat--nonperformance; naiskarmyam--freedom from reaction; purusah--man; asnute--achieve; na--nor; ca--also; sannyasanat--by renunciation; eva--simply; siddhim--success; samadhigacchati--attain. ', N'Not by merely abstaining from work can one achieve freedom from reaction, nor by renunciation alone can one attain perfection. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  5, N'na hi kascit ksanam api    jatu tisthaty akarma-krt    karyate hy avasah karma    sarvah prakrti-jair gunaih', N'na--nor; hi--certainly; kascit--anyone; ksanam--even a moment; api--also; jatu--even; tisthati--stands; akarma-krt--without doing something; karyate--forced to work; hi--certainly; avasah--helplessly;karma--work; sarvah--everything; prakrti-jaih--out of the modes of material nature; gunaih--by the qualities.', N'All men are forced to act helplessly according to the impulses born of the modes of material nature; therefore no one can refrain from doing something, not even for a moment.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  6, N'karmendriyani samyamya    ya aste manasa smaran    indriyarthan vimudhatma    mithyacarah sa ucyate', N'karma-indriyani--the five working sense organs; samyamya--controlling;yah--anyone who; aste--remains; manasa--by mind; smaran--thinking; indriya-arthan--sense objects; vimudha--foolish; atma--soul; mithyaacarah--pretender; sah--he; ucyate--is called. ', N'One who restrains the senses and organs of action, but whose mind dwells on sense objects, certainly deludes himself and is called a pretender.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  7, N'yas tv indriyani manasa    niyamyarabhate arjuna    karmendriyaih karma-yogam    asaktah sa visisyate', N'yah--one who; tu--but; indriyani--senses; manasa--by the mind; niyamya--regulating; arabhate--begins; arjuna--O Arjuna; karma-indriyaih--by the active sense organs; karma-yogam--devotion; asaktah--withoutattachment; sah--he; visisyate--by far the better. ', N'On the other hand, he who controls the senses by the mind and engages his active organs in works of devotion, without attachment, is by far superior.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  8, N'niyatam kuru karma tvam    karma jyayo hy akarmanah    sarira-yatrapi ca te    na prasiddhyed akarmanah', N'niyatam--prescribed; kuru--do; karma--duties; tvam--you; karma--work;jyayah--better; hi--than; akarmanah--without work; sarira--bodily; yatra--maintenance; api--even; ca--also; te--your; na--never;prasiddhyet--effected; akarmanah--without work. ', N'Perform your prescribed duty, for action is better than inaction. A man cannot even maintain his physical body without work. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  9, N'yajnarthat karmano nyatra    loko yam karma-bandhanah    tad-artham karma kaunteya    mukta-sangah samacara', N'yajna-arthat--only for the sake of Yajna, or Visnu; karmanah--workdone; anyatra--otherwise; lokah--this world; ayam--this; karmabandhanah-- bondage by work; tat--Him; artham--for the sake; karma--work; kaunteya--O son of Kunti; mukta-sangah--liberated from association; samacara--do perfectly.', N'Work done as a sacrifice for Visnu has to be performed, otherwise work binds one to this material world. Therefore, O son of Kunti, perform your prescribed duties for His satisfaction, and in that way you will always remain unattached and free from bondage.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  10, N'saha-yajnah prajah srstva    purovaca prajapatih    anena prasavisyadhvam    esa vo stv ista-kama-dhuk', N'saha--along with; yajnah--sacrifices; prajah--generations; srstva--creating; pura--anciently; uvaca--said; praja-patih--the Lord of creatures; anena--by this; prasavisyadhvam--be more and moreprosperous; esah--certainly; vah--your; astu--let it be; ista--all desirable; kama-dhuk--bestower.', N'In the beginning of creation, the Lord of all creatures sent forth generations of men and demigods, along with sacrifices for Visnu, and blessed them by saying, "Be thou happy by this yajna [sacrifice] because its performance will bestow upon you all desirable things."');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  11, N'devan bhavayatanena    te deva bhavayantu vah    parasparam bhavayantah    sreyah param avapsyatha', N'devan--demigods; bhavayata--having pleased; anena--by this sacrifice;te--those; devah--the demigods; bhavayantu--will please; vah--you; parasparam--mutual; bhavayantah--pleasing one another; sreyah--benediction; param--the supreme; avapsyatha--do you achieve. ', N'The demigods, being pleased by sacrifices, will also please you; thus nourishing one another, there will reign general prosperity for all. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  12, N'istan bhogan hi vo deva    dasyante yajna-bhavitah    tair dattan apradayaibhyo    yo bhunkte stena eva sah', N'istan--desired; bhogan--necessities of life; hi--certainly; vah--untoyou; devah--the demigods; dasyante--award; yajna-bhavitah--being satisfied by the performance of sacrifices; taih--by them; dattan--things given; apradaya--without offering; ebhyah--to the demigods; yah- -he who; bhunkte--enjoys; stenah--thief; eva--certainly; sah--is he.', N'In charge of the various necessities of life, the demigods, being satisfied by the performance of yajna [sacrifice], supply all necessities to man. But he who enjoys these gifts without offering them to the demigods in return is certainly a thief.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  13, N'yajna-sistasinah santo    mucyante sarva-kilbisaih    bhunjate te tv agham papa    ye pacanty atma-karanat', N'yajna-sista--food taken after performance of yajna; asinah--eaters;santah--the devotees; mucyante--get relief from; sarva--all kinds of; kilbisaih--from sins; bhunjate--enjoy; te--they; tu--but; agham--grievous sins; papah--sinners; ye--those; pacanti--prepare food; atmakaranat-- for sense enjoyment.', N'The devotees of the Lord are released from all kinds of sins because they eat food which is offered first for sacrifice. Others, who prepare food for personal sense enjoyment, verily eat only sin.  ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  14, N'annad bhavanti bhutani    parjanyad anna-sambhavah    yajnad bhavati parjanyo    yajnah karma-samudbhavah', N'annat--from grains; bhavanti--grow; bhutani--the material bodies;parjanyat--from rains; anna--of food grains; sambhavah--are made possible; yajnat--from the performance of sacrifice; bhavati--becomespossible; parjanyah--rains; yajnah--performance of yajna; karma-- prescribed duties; samudbhavah--born of.', N'All living bodies subsist on food grains, which are produced from rains. Rains are produced by performance of yajna [sacrifice], and yajna is born of prescribed duties.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3, 15, N'karma brahmodbhavam viddhi    brahmaksara-samudbhavam    tasmat sarva-gatam brahma    nityam yajne pratisthitam', N'karma--work; brahma--Vedas; udbhavam--produced from; viddhi--one shouldknow; brahma--the Vedas; aksara--the Supreme Brahman (Personality of Godhead); samudbhavam--directly manifested; tasmat--therefore; sarvagatam--all-pervading; brahma--transcendence; nityam--eternally; yajne-- in sacrifice; pratisthitam--situated.', N'Regulated activities are prescribed in the Vedas, and the Vedas are directly manifested from the Supreme Personality of Godhead. Consequently the all-pervading Transcendence is eternally situated in acts of sacrifice.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  16, N'evam pravartitam cakram    nanuvartayatiha yah    aghayur indriyaramo    mogham partha sa jivati', N'evam--thus prescribed; pravartitam--established by the Vedas; cakram--cycle; na--does not; anuvartayati--adopt; iha--in this life; yah--one who; agha-ayuh--life full of sins; indriya-aramah--satisfied in sensegratification; mogham--useless; partha--O son of Prtha (Arjuna); sah-- one who does so; jivati--lives.', N'My dear Arjuna, a man who does not follow this prescribed Vedic system of sacrifice certainly leads a life full of sin, for a person delighting only in the senses lives in vain.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  17, N'yas tv atma-ratir eva syad    atma-trptas ca manavah    atmany eva ca santustas    tasya karyam na vidyate', N'yah--one who; tu--but; atma-ratih--takes pleasure; eva--certainly;syat--remains; atma-trptah--self-illuminated; ca--and; manavah--a man; atmani--in himself; eva--only; ca--and; santustah--perfectly satiated;tasya--his; karyam--duty; na--does not; vidyate--exist. ', N'One who is, however, taking pleasure in the self, who is illuminated in the self, who rejoices in and is satisfied with the self only, fully satiated--for him there is no duty.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  18, N'naiva tasya krtenartho    nakrteneha kascana    na casya sarva-bhutesu    kascid artha-vyapasrayah', N'na--never; eva--certainly; tasya--his; krtena--by discharge of duty;arthah--purpose; na--nor; akrtena--without discharge of duty; iha--in this world; kascana--whatever; na--never; ca--and; asya--of him; sarvabhutesu--in all living beings; kascit--any; artha--purpose; vyapasrayah--taking shelter of.', N'A self-realized man has no purpose to fulfill in the discharge of his prescribed duties, nor has he any reason not to perform such work. Nor has he any need to depend on any other living being.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  19, N'tasmad asaktah satatam    karyam karma samacara    asakto hy acaran karma    param apnoti purusah', N'tasmat--therefore; asaktah--without attachment; satatam--constantly;karyam--as duty; karma--work; samacara--perform; asaktah--nonattached; hi--certainly; acaran--performing; karma--work; param--the Supreme;apnoti--achieves; purusah--a man. ', N'Therefore, without being attached to the fruits of activities, one should act as a matter of duty; for by working without attachment one attains the Supreme.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  20, N'karmanaiva hi samsiddhim    asthita janakadayah    loka-sangraham evapi    sampasyan kartum arhasi', N'karmana--by work; eva--even; hi--certainly; samsiddhim--perfection;asthitah--situated; janaka-adayah--Janaka and other kings; lokasangraham-- educating the people in general; eva--also; api--for thesake of; sampasyan--by considering; kartum--to act; arhasi--deserve. ', N'Kings such as Janaka and others attained the perfectional stage by performance of prescribed duties. Therefore, just for the sake of educating the people in general, you should perform your work.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  21, N'yad yad acarati sresthas    tat tad evetaro janah    sa yat pramanam kurute    lokas tad anuvartate', N'yat--whatever; yat--and whichever; acarati--does he act; sresthah--arespectable leader; tat--that; tat--and that alone; eva--certainly; itarah--common; janah--person; sah--he; yat--whichever; pramanam--evidence; kurute--does perform; lokah--all the world; tat--that; anuvartate--follow in the footsteps.', N'Whatever action is performed by a great man, common men follow in his footsteps. And whatever standards he sets by exemplary acts, all the world pursues.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  22, N'na me parthasti kartavyam    trisu lokesu kincana    nanavaptam avaptavyam    varta eva ca karmani', N'na--not; me--Mine; partha--O son of Prtha; asti--there is; kartavyam--any prescribed duty; trisu--in the three; lokesu--planetary systems; kincana--anything; na--no; anavaptam--in want; avaptavyam--to begained; varte--engaged; eva--certainly; ca--also; karmani--in one  prescribed duty.', N'O son of Prtha, there is no work prescribed for Me within all the three planetary systems. Nor am I in want of anything, nor have I need to obtain anything--and yet I am engaged in work.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  23, N'yadi hy aham na varteyam    jatu karmany atandritah    mama vartmanuvartante    manusyah partha sarvasah', N'yadi--if; hi--certainly; aham--I; na--do not; varteyam--thus engage;jatu--ever; karmani--in the performance of prescribed duties; atandritah--with great care; mama--My; vartma--path; anuvartante--wouldfollow; manusyah--all men; partha--O son of Prtha; sarvasah--in all respects.', N'For if I did not engage in work, O Partha, certainly all men would follow My path. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  24, N'utsideyur ime loka    na kuryam karma ced aham    sankarasya ca karta syam    upahanyam imah prajah', N'utsideyuh--put into ruin; ime--all these; lokah--worlds; na--do not;kuryam--perform; karma--prescribed duties; cet--if; aham--I; sankarasya--of unwanted population; ca--and; karta--creator; syam--shall be; upahanyam--destroy; imah--all these; prajah--living entities. ', N'If I should cease to work, then all these worlds would be put to ruination. I would also be the cause of creating unwanted population, and I would thereby destroy the peace of all sentient beings.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  25, N'saktah karmany avidvamso    yatha kurvanti bharata    kuryad vidvams tathasaktas    cikirsur loka-sangraham', N'saktah--being attached; karmani--prescribed duties; avidvamsah--theignorant; yatha--as much as; kurvanti--do it; bharata--O descendant of Bharata; kuryat--must do; vidvan--the learned; tatha--thus; asaktah--without attachment; cikirsuh--desiring to; loka-sangraham--leading the people in general.', N'As the ignorant perform their duties with attachment to results, similarly the learned may also act, but without attachment, for the sake of leading the people on the right path.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  26, N'na buddhi-bhedam janayed    ajnanam karma-sanginam    josayet sarva-karmani    vidvan yuktah samacaran', N'na--do not; buddhi-bhedam--disrupt the intelligence; janayet--do;ajnanam--of the foolish; karma-sanginam--attached to fruitive work; josayet--dovetailed; sarva--all; karmani--work; vidvan--learned;yuktah--all engaged; samacaran--practicing. ', N'Let not the wise disrupt the minds of the ignorant who are attached to fruitive action, they should not be encouraged to refrain from work, but to engage in work in the spirit of devotion.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  27, N'prakrteh kriyamanani    gunaih karmani sarvasah    ahankara-vimudhatma    kartaham iti manyate', N'prakrteh--of material nature; kriyamanani--all being done; gunaih--bythe modes; karmani--activities; sarvasah--all kinds of; ahankaravimudha-- bewildered by false ego; atma--the spirit soul; karta--doer;aham--I; iti--thus; manyate--thinks. ', N'The bewildered spirit soul, under the influence of the three modes of material nature, thinks himself to be the doer of activities, which are in actuality carried out by nature.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  28, N'tattva-vit tu maha-baho    guna-karma-vibhagayoh    guna gunesu vartanta    iti matva na sajjate', N'tattva-vit--the knower of the Absolute Truth; tu--but; maha-baho--Omighty-armed one; guna-karma--works under material influence; vibhagayoh--differences; gunah--senses; gunesu--in sense gratification;vartante--being engaged; iti--thus; matva--thinking; na--never; sajjate--becomes attached.', N'One who is in knowledge of the Absolute Truth, O mighty-armed, does not engage himself in the senses and sense gratification, knowing well the differences between work in devotion and work for fruitive results.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  29, N'prakrter guna-sammudhah    sajjante guna-karmasu    tan akrtsna-vido mandan    krtsna-vin na vicalayet', N'prakrteh--impelled by the material modes; guna-sammudhah--befooled bymaterial identification; sajjante--become engaged; guna-karmasu--in material activities; tan--all those; akrtsna-vidah--persons with a poorfund of knowledge; mandan--lazy to understand self-realization; krtsnavit-- one who is in factual knowledge; na--may not; vicalayet--try to agitate.', N'Bewildered by the modes of material nature, the ignorant fully engage themselves in material activities and become attached. But the wise should not unsettle them, although these duties are inferior due to the performers lack of knowledge.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  30, N'mayi sarvani karmani    sannyasyadhyatma-cetasa    nirasir nirmamo bhutva    yudhyasva vigata-jvarah', N'mayi--unto Me; sarvani--all sorts of; karmani--activities; sannyasya--giving up completely; adhyatma--with full knowledge of the self; cetasa--consciousness; nirasih--without desire for profit; nirmamah--without ownership; bhutva--so being; yudhyasva--fight; vigata-jvarah-- without being lethargic.', N'Therefore, O Arjuna, surrendering all your works unto Me, with mind intent on Me, and without desire for gain and free from egoism and lethargy, fight.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  31, N'ye me matam idam nityam    anutisthanti manavah    sraddhavanto nasuyanto    mucyante te pi karmabhih', N'ye--those; me--My; matam--injunctions; idam--this; nityam--eternalfunction; anutisthanti--execute regularly; manavah--humankind; sraddhavantah-- with faith and devotion; anasuyantah--without envy; mucyante--become free; te--all of them; api--even; karmabhih--from the bondage of the law of fruitive action.', N'One who execute his duties according to My injunctions and who follows this teaching faithfully, without envy, becomes free from the bondage of fruitive actions.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  32, N'ye tv etad abhyasuyanto    nanutisthanti me matam    sarva-jnana-vimudhams tan    viddhi nastan acetasah', N'ye--those; tu--however; etat--this; abhyasuyantah--out of envy; na--donot; anutisthanti--regularly perform; me--My; matam--injunction; sarvajnana-- all sorts of knowledge; vimudhan--perfectly befooled; tan--theyare; viddhi--know it well; nastan--all ruined; acetasah--without Krsna consciousness.', N'But those who, out of envy disregard these teachings and do not practice them regularly, are to be considered bereft of all knowledge, befooled, and doomed to ignorance and bondage.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  33, N'sadrsam cestate svasyah    prakrter jnanavan api    prakrtim yanti bhutani    nigrahah kim karisyati', N'sadrsam--accordingly; cestate--tries; svasyah--in one  own nature;prakrteh--modes; jnana-van--learned; api--although; prakrtim--nature; yanti--undergo; bhutani--all living entities; nigrahah--suppression;kim--what; karisyati--can do. ', N'Even a man of knowledge acts according to his own nature, for everyone follows his nature. What can repression accomplish? ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  34, N'indriyasyendriyasyarthe    raga-dvesau vyavasthitau    tayor na vasam agacchet    tau hy asya paripanthinau', N'indriyasya--of the senses; indriyasya arthe--in the sense objects;raga--attachment; dvesau--also detachment; vyavasthitau--put under regulations; tayoh--of them; na--never; vasam--control; agacchet--oneshould come; tau--those; hi--certainly; asya--his; paripanthinau-- stumbling blocks.', N'Attraction and repulsion for sense objects are felt by embodied beings, but one should not fall under the control of senses and sense objects because they are stumbling blocks on the path of self-realization.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  35, N'sreyan sva-dharmo vigunah    para-dharmat sv-anusthitat    sva-dharme nidhanam sreyah    para-dharmo bhayavahah', N'sreyan--far better; sva-dharmah--one  prescribed duties; vigunah--evenfaulty; para-dharmat--from duties mentioned for others; su-anusthitat-- than perfectly done; sva-dharme--in one  prescribed duties; nidhanam--destruction; sreyah--better; para-dharmah--duties prescribed for others; bhaya-avahah--dangerous.', N'It is far better to discharge one  prescribed duties, even though they may be faultily, than another  duties. Destruction in the course of performing one s own duty is better than engaging in another  duties, for to follow another  path is dangerous.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  36, N'arjuna uvaca    atha kena prayukto yam    papam carati purusah    anicchann api varsneya    balad iva niyojitah', N'arjunah uvaca--Arjuna said; atha--hereafter; kena--by what; prayuktah--impelled; ayam--one; papam--sins; carati--acts; purusah--a man; anicchan--without desiring; api--although; varsneya--O descendant ofVrsni; balat--by force; iva--as if; niyojitah--engaged. ', N'Arjuna said: O descendant of Vrsni, by what is one impelled to sinful acts, even unwillingly, as if engaged by force? ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  37, N'sri-bhagavan uvaca    kama esa krodha esa    rajo-guna-samudbhavah    mahasano maha-papma    viddhy enam iha vairinam', N'sri-bhagavan uvaca--the Personality of Godhead said; kamah--lust; esah--all these; krodhah--wrath; esah--all these; rajah-guna--the mode of passion; samudbhavah--born of; maha-asanah--all-devouring; maha-papma--greatly sinful; viddhi--know; enam--this; iha--in the material world; vairinam--greatest enemy.', N'The Blessed Lord said: It is lust only, Arjuna, which is born of contact with the material mode of passion and later transformed into wrath, and which is the all-devouring, sinful enemy of this world.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  38, N'dhumenavriyate vahnir    yathadarso malena ca    yatholbenavrto garbhas    tatha tenedam avrtam', N'dhumena--by smoke; avriyate--covered; vahnih--fire; yatha--just as;adarsah--mirror; malena--by dust; ca--also; yatha--just as; ulbena--by the womb; avrtah--is covered; garbhah--embryo; tatha--so; tena--by thatlust; idam--this; avrtam--is covered. ', N'As fire is covered by smoke, as a mirror is covered by dust, or as the embryo is covered by the womb, similarly, the living entity is covered by different degrees of this lust.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  39, N'avrtam jnanam etena    jnanino nitya-vairina    kama-rupena kaunteya    duspurenanalena ca', N'avrtam--covered; jnanam--pure consciousness; etena--by this; jnaninah--of the knower; nitya-vairina--eternal enemy; kama-rupena--in the form of lust; kaunteya--O son of Kunti; duspurena--never to be satisfied;analena--by the fire; ca--also. ', N'Thus, a man  pure consciousness is covered by his eternal enemy in the form of lust, which is never satisfied and which burns like fire. ');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  40, N'indriyani mano buddhir    asyadhisthanam ucyate    etair vimohayaty esa    jnanam avrtya dehinam', N'indriyani--the senses; manah--the mind; buddhih--the intelligence;asya--of the lust; adhisthanam--sitting place; ucyate--called; etaih-- by all these; vimohayati--bewilders; esah--of this; jnanam--knowledge;avrtya--covering; dehinam--the embodied. ', N'The senses, the mind and the intelligence are the sitting places of this lust, which veils the real knowledge of the living entity and bewilders him.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  41, N'tasmat tvam indriyany adau    niyamya bharatarsabha    papmanam prajahi hy enam    jnana-vijnana-nasanam', N'tasmat--therefore; tvam--you; indriyani--senses; adau--in thebeginning; niyamya--by regulating; bharata-rsabha--O chief amongst the descendants of Bharata; papmanam--the great symbol of sin; prajahi--curb; hi--certainly; enam--this; jnana--knowledge; vijnana--scientific knowledge of the pure soul; nasanam--the destroyer.', N'Therefore, O Arjuna, best of the Bharatas, in the very beginning curb this great symbol of sin [lust] by regulating the senses, and slay this destroyer of knowledge and self-realization.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  42, N'indriyani parany ahur    indriyebhyah param manah    manasas tu para buddhir    yo buddheh paratas tu sah', N'indriyani--senses; parani--superior; ahuh--is said; indriyebhyah--morethan the senses; param--superior; manah--the mind; manasah--more than the mind; tu--also; para--superior; buddhih--intelligence; yah--onewho; buddheh--more than the intelligence; paratah--superior; tu--but; sah--he.', N'The working senses are superior to dull matter; mind is higher than the senses; intelligence is still higher than the mind; and he [the soul] is even higher than the intelligence.');

INSERT [dbo].[Cards] ([Id], [Chapter], [Verse], [Description], [Synonmys], [Meaning]) 
VALUES (NEWID(), 3,  43, N'evam buddheh param buddhva    samstabhyatmanam atmana    jahi satrum maha-baho    kama-rupam durasadam', N'evam--thus; buddheh--of intelligence; param--superior; buddhva--soknowing; samstabhya--by steadying; atmanam--of the mind; atmana--by deliberate intelligence; jahi--conquer; satrum--the enemy; maha-baho--Omighty-armed one; kama-rupam--the form of lust; durasadam--formidable. ', N'Thus knowing oneself to be transcendental to material senses, mind and intelligence, one should control the lower self by the higher self and thus--by spiritual strength--conquer this insatiable enemy known as lust.');

