version: 2.1

orbs:
win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default     
  
    steps:
      - checkout
      - run: dotnet build

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud